model:
  name: "microsoft/deberta-v3-xsmall"
  max_num_labels: 10

training:
  num_steps: 1000 
  batch_size: 32
  learning_rate: 2e-5
  optimizer: "adamw"
  epochs : 50

data:
  data_path: "/content/drive/MyDrive/Projet Urchadee/Cross encoder : multilabel classification/data/data.json"
  